# Generated by Django 4.2.3 on 2023-07-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='about',
            field=models.TextField(max_length=400),
        ),
    ]
